window.addEventListener("load", () => {
  let heroes = [
    {
      name: "Ana",
      emoji1: "🎯",
      emoji2: "💉",
      emoji3: "👵",
      emoji4: "😴",
    },
    {
      name: "Ashe",
      emoji1: "🎯",
      emoji2: "🤠",
      emoji3: "🧨",
    },
    {
      name: "Baptiste",
      emoji1: "🩹",
      emoji2: "🔫",
      emoji3: "🙍🏿‍♂️",
    },
    {
      name: "Bastion",
      emoji1: "🤖",
      emoji2: "🐤",
      emoji2: "💣",
      emoji3: "🔫",
    },
    {
      name: "Brigitte",
      emoji1: "🐱",
      emoji2: "🛡",
      emoji3: "🩹",
    },
    {
      name: "Cassidy",
      emoji1: "🤠",
      emoji2: "🚬",
      emoji3: "🔫",
      emoji4: "🦾",
    },
    {
      name: "D.Va",
      emoji1: "🎮",
      emoji2: "🚀",
      emoji3: "🐰",
    },
    {
      name: "Doomfist",
      emoji1: "🥋",
      emoji2: "🦾",
      emoji3: "👊🏿",
    },
    {
      name: "Echo",
      emoji1: "🤖",
      emoji2: "👩🏻‍⚕️",
      emoji3: "🔃",
      emoji4: "👩🏻",
    },
    {
      name: "Genji",
      emoji1: "🐱‍👤",
      emoji2: "⭐",
      emoji3: "🗡️",
    },
    {
      name: "Hanzo",
      emoji1: "🍡",
      emoji2: "🍣",
      emoji3: "🏹",
      emoji4: "🏯",
    },
    {
      name: "Hazard",
      emoji1: "🦾",
      emoji2: "⛓️",
    },
    {
      name: "Illari",
      emoji1: "🩹",
      emoji2: "☀️",
    },
    {
      name: "Junker Queen",
      emoji1: "🗑️",
      emoji2: "🔪",
      emoji3: "👑",
    },
    {
      name: "Junkrat",
      emoji1: "🗑️",
      emoji2: "💣",
      emoji3: "🐀",
    },
    {
      name: "Juno",
      emoji1: "🩹",
      emoji2: "☄️",
      emoji3: "🪐",
      emoji4: "😰",
    },
    {
      name: "Kiriko",
      emoji1: "🩹",
      emoji2: "🏯",
      emoji3: "🦊",
    },
    {
      name: "Lifeweaver",
      emoji1: "🩹",
      emoji2: "🌲",
      emoji3: "🌸",
    },
    {
      name: "Lucio",
      emoji1: "🩹",
      emoji2: "🎧",
      emoji3: "🐸",
    },
    {
      name: "Mauga",
      emoji1: "🔫",
      emoji2: "🔫",
      emoji3: "🔥",
      emoji4: "💪🏽",
    },
    {
      name: "Mei",
      emoji1: "🐼",
      emoji2: "❄",
      emoji3: "🧊",
    },
  ];
});
